

[shell]
program = "/usr/bin/fish"

[window]
decorations = "Buttonless"

[window.padding]
x=16
y=16


[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[font.offset]
y=8

# Colors (Gruvbox light)

# Default colors
[colors.primary]
# background = '#f9f5d7'
# background = '#fbf1c7'
# background = '#f2e5bc'
background = '#f9f2c7'
foreground = '#3c3836'

# Normal colors
[colors.normal]
black   = '#fbf2c7'
red     = '#cc241d'
green   = '#98971a'
yellow  = '#d79921'
blue    = '#458588'
magenta = '#b16286'
cyan    = '#689d6a'
white   = '#7c6f64'

# Bright colors
[colors.bright]
black   = '#928374'
red     = '#9d0006'
green   = '#79740e'
yellow  = '#b57614'
blue    = '#076678'
magenta = '#8f3f71'
cyan    = '#427b58'
white   = '#3c3836'
